[package]
name = "raytracer"
version = "0.1.0"
authors = ["Sean Humeniuk <seanhumeniuk@gmail.com>"]

[dependencies]
rand = "*"
image = "*"
toml = "*"
tdmath = { path = "../tdmath" }
cmdpro = { path = "../cmdpro" }
